### PR TITLE
Save dark mode choice in localStorage

### LINKED ISSUE #1: Save Theme Choice
Hi Jason!

I like this project and only have one suggestion: is there a way to save the user's theme choice? I'm willing and able to make a PR to do it, but I'm not sure if this is something you'd merge. Would you be interested in merging a PR for this?

### PR DESCRIPTION
**Pull request by SConaway**
Seems to work, although it throws this warning (dev mode only) if started into dark mode:

```
Prop `className` did not match. Server: "jsx-85500106 " Client: "jsx-822878187 "
```

Closes #1.

I'm glad `localStorage.getItem()` is not async....that would have made everything a LOT harder.

### CODE REVIEW

**Comment by SConaway** [comment]
If you're open to it, we can implement this `useEffect` from the mui example: https://github.com/mui-org/material-ui/blob/b0e10a1805ad7abd6f3c368bfbf63f4d85d29b47/examples/nextjs/pages/_app.js#L11-L17, but I don't think it's really an issue.

**Comment by jasonappah** [comment]
I tried to figure out what the issue was but I genuinely have no idea what's up. Everything appears to be working though, so I'll merge. Thanks for the PR!

**Comment by SConaway** [comment]
And of course, I just noticed a bug with the buttons — they appear white even when the theme should be black. I'll look into it.

**Comment by jasonappah** [comment]
Awesome, thanks!

**Pull request merged**
